version: '3'

tasks:
  default:
    cmds:
      - echo "This is task cmd"
    silent: true
  
  build:
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -o bin/main cmd/main.go
    silent: true
  run:
    cmds:
      - ./bin/main
    deps:
      - build
    silent: true

  build-mage:
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -o ./mage mage-tools/mage.go
    silent: true
  
  build-gg:
    cmds:
      - ./mage -d mage-tools -compile ../gg
    deps:
      - build-mage
    silent: true

  coverage:
    cmds:
      - go test -v -cover ./...
    silent: true
  test:
    cmds:
      - go test -v ./...
    silent: true
  